repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.0
  hooks:
    - id: nbqa-ruff
      additional_dependencies: [ruff]
    - id: nbqa-ruff-format
      additional_dependencies: [ruff]
