repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [--target-version=py37]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==22.3.0]
      args: []
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.10.0]
      args: [--py37-plus]
    - id: nbqa-isort
      additional_dependencies: [isort==5.7.0]
      args: [--float-to-top]
