name: binder-environment
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - slycot
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - ipywidgets
  - pip:
    - control
    - jupyter
    - OMPython>=3.3.0
    - opencv-python>=4.8.0
    - pytesseract>=0.3.10
    - Pillow>=10.0.0
